language: rust

services:
  - docker

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

cache: cargo

deploy:
  provider: script
  script: ./.travis/docker-push
  on:
    branch: develop
    condition: $TRAVIS_RUST_VERSION = stable

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
